on: [push]

jobs:
  CodeAnalysis:
    runs-on: ubuntu-latest
    name: code analysis
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Tencent Cloud Code Analysis
        uses: ./
        with:
          block: false
          label: open-standard